version: 2.1

jobs:
  deploy:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Set up AWS credentials
          command: echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY > ~/.env
      - run:
          name: Initializing the Terraform code
          command: |
            cd ./terraform-files
            terraform init
      - run:
          name: Terraform Plan (with unlock)
          command: |
            cd ./terraform-files
            terraform force-unlock -force afaa7c48-e5c9-52b7-4681-b04ac6f0fef0 || true
            terraform plan -var-file=variables.tfvars
      - run:
          name: Terraform Apply
          command: |
            cd ./terraform-files
            terraform apply --auto-approve -var-file=variables.tfvars

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    environment:
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - checkout
      - run:
          name: Set up AWS credentials
          command: echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY > ~/.env
      - run:
          name: Initializing the Terraform code
          command: |
            cd ./terraform-files
            terraform init
      - run:
          name: Terraform plan (with unlock)
          command: |
            cd ./terraform-files
            
            
            terraform plan -var-file=variables.tfvars
      - run:
          name: Terraform Apply (optional, if needed)
          command: |
            cd ./terraform-files
          
            terraform apply --auto-approve -var-file=variables.tfvars
      - run:
          name: Terraform Destroy
          command: |
            cd ./terraform-files
            
            terraform destroy --auto-approve -var-file=variables.tfvars

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy

  destroy-infrastructure:
    jobs:
      - destroy
